<?php

# Don't touch this code. This is auto generated.

namespace ryunosuke\Functions\Package;

# constants
if (!defined("ryunosuke\\Functions\\Package\\IS_OWNSELF")) {
    /** 自分自身を表す定数 */
    define("ryunosuke\\Functions\\Package\\IS_OWNSELF", 128);
}

if (!defined("ryunosuke\\Functions\\Package\\IS_PUBLIC")) {
    /** public を表す定数 @see \ReflectionProperty::IS_PUBLIC */
    define("ryunosuke\\Functions\\Package\\IS_PUBLIC", 256);
}

if (!defined("ryunosuke\\Functions\\Package\\IS_PROTECTED")) {
    /** protected を表す定数 @see \ReflectionProperty::IS_PROTECTED */
    define("ryunosuke\\Functions\\Package\\IS_PROTECTED", 512);
}

if (!defined("ryunosuke\\Functions\\Package\\IS_PRIVATE")) {
    /** private を表す定数 @see \ReflectionProperty::IS_PRIVATE */
    define("ryunosuke\\Functions\\Package\\IS_PRIVATE", 1024);
}

if (!defined("ryunosuke\\Functions\\Package\\JP_ERA")) {
    /** 和暦 */
    define("ryunosuke\\Functions\\Package\\JP_ERA", [
        [
            "name"  => "令和",
            "abbr"  => "R",
            "since" => 1556636400,
        ],
        [
            "name"  => "平成",
            "abbr"  => "H",
            "since" => 600188400,
        ],
        [
            "name"  => "昭和",
            "abbr"  => "S",
            "since" => -1357635600,
        ],
        [
            "name"  => "大正",
            "abbr"  => "T",
            "since" => -1812186000,
        ],
        [
            "name"  => "明治",
            "abbr"  => "M",
            "since" => -3216790800,
        ],
    ]);
}

if (!defined("ryunosuke\\Functions\\Package\\KEYWORDS")) {
    /** SQL キーワード（全 RDBMS ごちゃまぜ） */
    define("ryunosuke\\Functions\\Package\\KEYWORDS", [
        ""  => "",
        0   => "ACCESSIBLE",
        1   => "ACTION",
        2   => "ADD",
        3   => "AFTER",
        4   => "AGAINST",
        5   => "AGGREGATE",
        6   => "ALGORITHM",
        7   => "ALL",
        8   => "ALTER",
        9   => "ALTER TABLE",
        10  => "ANALYSE",
        11  => "ANALYZE",
        12  => "AND",
        13  => "AS",
        14  => "ASC",
        15  => "AUTOCOMMIT",
        16  => "AUTO_INCREMENT",
        17  => "BACKUP",
        18  => "BEGIN",
        19  => "BETWEEN",
        20  => "BINLOG",
        21  => "BOTH",
        22  => "CASCADE",
        23  => "CASE",
        24  => "CHANGE",
        25  => "CHANGED",
        26  => "CHARACTER SET",
        27  => "CHARSET",
        28  => "CHECK",
        29  => "CHECKSUM",
        30  => "COLLATE",
        31  => "COLLATION",
        32  => "COLUMN",
        33  => "COLUMNS",
        34  => "COMMENT",
        35  => "COMMIT",
        36  => "COMMITTED",
        37  => "COMPRESSED",
        38  => "CONCURRENT",
        39  => "CONSTRAINT",
        40  => "CONTAINS",
        41  => "CONVERT",
        42  => "CREATE",
        43  => "CROSS",
        44  => "CURRENT_TIMESTAMP",
        45  => "DATABASE",
        46  => "DATABASES",
        47  => "DAY",
        48  => "DAY_HOUR",
        49  => "DAY_MINUTE",
        50  => "DAY_SECOND",
        51  => "DEFAULT",
        52  => "DEFINER",
        53  => "DELAYED",
        54  => "DELETE",
        55  => "DELETE FROM",
        56  => "DESC",
        57  => "DESCRIBE",
        58  => "DETERMINISTIC",
        59  => "DISTINCT",
        60  => "DISTINCTROW",
        61  => "DIV",
        62  => "DO",
        63  => "DROP",
        64  => "DUMPFILE",
        65  => "DUPLICATE",
        66  => "DYNAMIC",
        67  => "ELSE",
        68  => "ENCLOSED",
        69  => "END",
        70  => "ENGINE",
        71  => "ENGINES",
        72  => "ENGINE_TYPE",
        73  => "ESCAPE",
        74  => "ESCAPED",
        75  => "EVENTS",
        76  => "EXCEPT",
        77  => "EXECUTE",
        78  => "EXISTS",
        79  => "EXPLAIN",
        80  => "EXTENDED",
        81  => "FAST",
        82  => "FIELDS",
        83  => "FILE",
        84  => "FIRST",
        85  => "FIXED",
        86  => "FLUSH",
        87  => "FOR",
        88  => "FORCE",
        89  => "FOREIGN",
        90  => "FROM",
        91  => "FULL",
        92  => "FULLTEXT",
        93  => "FUNCTION",
        94  => "GLOBAL",
        95  => "GRANT",
        96  => "GRANTS",
        97  => "GROUP",
        98  => "GROUP_CONCAT",
        99  => "HAVING",
        100 => "HEAP",
        101 => "HIGH_PRIORITY",
        102 => "HOSTS",
        103 => "HOUR",
        104 => "HOUR_MINUTE",
        105 => "HOUR_SECOND",
        106 => "IDENTIFIED",
        107 => "IF",
        108 => "IFNULL",
        109 => "IGNORE",
        110 => "IN",
        111 => "INDEX",
        112 => "INDEXES",
        113 => "INFILE",
        114 => "INNER",
        115 => "INSERT",
        116 => "INSERT_ID",
        117 => "INSERT_METHOD",
        118 => "INTERSECT",
        119 => "INTERVAL",
        120 => "INTO",
        121 => "INVOKER",
        122 => "IS",
        123 => "ISOLATION",
        124 => "JOIN",
        125 => "JSON_ARRAY",
        126 => "JSON_ARRAY_APPEND",
        127 => "JSON_ARRAY_INSERT",
        128 => "JSON_CONTAINS",
        129 => "JSON_CONTAINS_PATH",
        130 => "JSON_DEPTH",
        131 => "JSON_EXTRACT",
        132 => "JSON_INSERT",
        133 => "JSON_KEYS",
        134 => "JSON_LENGTH",
        135 => "JSON_MERGE_PATCH",
        136 => "JSON_MERGE_PRESERVE",
        137 => "JSON_OBJECT",
        138 => "JSON_PRETTY",
        139 => "JSON_QUOTE",
        140 => "JSON_REMOVE",
        141 => "JSON_REPLACE",
        142 => "JSON_SEARCH",
        143 => "JSON_SET",
        144 => "JSON_STORAGE_SIZE",
        145 => "JSON_TYPE",
        146 => "JSON_UNQUOTE",
        147 => "JSON_VALID",
        148 => "KEY",
        149 => "KEYS",
        150 => "KILL",
        151 => "LAST_INSERT_ID",
        152 => "LEADING",
        153 => "LEFT",
        154 => "LEVEL",
        155 => "LIKE",
        156 => "LIMIT",
        157 => "LINEAR",
        158 => "LINES",
        159 => "LOAD",
        160 => "LOCAL",
        161 => "LOCK",
        162 => "LOCKS",
        163 => "LOGS",
        164 => "LOW_PRIORITY",
        165 => "MARIA",
        166 => "MASTER",
        167 => "MASTER_CONNECT_RETRY",
        168 => "MASTER_HOST",
        169 => "MASTER_LOG_FILE",
        170 => "MATCH",
        171 => "MAX_CONNECTIONS_PER_HOUR",
        172 => "MAX_QUERIES_PER_HOUR",
        173 => "MAX_ROWS",
        174 => "MAX_UPDATES_PER_HOUR",
        175 => "MAX_USER_CONNECTIONS",
        176 => "MEDIUM",
        177 => "MERGE",
        178 => "MINUTE",
        179 => "MINUTE_SECOND",
        180 => "MIN_ROWS",
        181 => "MODE",
        182 => "MODIFY",
        183 => "MONTH",
        184 => "MRG_MYISAM",
        185 => "MYISAM",
        186 => "NAMES",
        187 => "NATURAL",
        188 => "NOT",
        189 => "NOW()",
        190 => "NULL",
        191 => "OFFSET",
        192 => "ON",
        193 => "ON DELETE",
        194 => "ON UPDATE",
        195 => "OPEN",
        196 => "OPTIMIZE",
        197 => "OPTION",
        198 => "OPTIONALLY",
        199 => "OR",
        200 => "ORDER",
        201 => "BY",
        202 => "OUTER",
        203 => "OUTFILE",
        204 => "PACK_KEYS",
        205 => "PAGE",
        206 => "PARTIAL",
        207 => "PARTITION",
        208 => "PARTITIONS",
        209 => "PASSWORD",
        210 => "PRIMARY",
        211 => "PRIVILEGES",
        212 => "PROCEDURE",
        213 => "PROCESS",
        214 => "PROCESSLIST",
        215 => "PURGE",
        216 => "QUICK",
        217 => "RAID0",
        218 => "RAID_CHUNKS",
        219 => "RAID_CHUNKSIZE",
        220 => "RAID_TYPE",
        221 => "RANGE",
        222 => "READ",
        223 => "READ_ONLY",
        224 => "READ_WRITE",
        225 => "REFERENCES",
        226 => "REGEXP",
        227 => "RELOAD",
        228 => "RENAME",
        229 => "REPAIR",
        230 => "REPEATABLE",
        231 => "REPLACE",
        232 => "REPLICATION",
        233 => "RESET",
        234 => "RESTORE",
        235 => "RESTRICT",
        236 => "RETURN",
        237 => "RETURNS",
        238 => "REVOKE",
        239 => "RIGHT",
        240 => "RLIKE",
        241 => "ROLLBACK",
        242 => "ROLLUP",
        243 => "ROW",
        244 => "ROWS",
        245 => "ROW_FORMAT",
        246 => "SECOND",
        247 => "SECURITY",
        248 => "SELECT",
        249 => "SEPARATOR",
        250 => "SERIALIZABLE",
        251 => "SESSION",
        252 => "SET",
        253 => "SHARE",
        254 => "SHOW",
        255 => "SHUTDOWN",
        256 => "SLAVE",
        257 => "SONAME",
        258 => "SOUNDS",
        259 => "SQL",
        260 => "SQL_AUTO_IS_NULL",
        261 => "SQL_BIG_RESULT",
        262 => "SQL_BIG_SELECTS",
        263 => "SQL_BIG_TABLES",
        264 => "SQL_BUFFER_RESULT",
        265 => "SQL_CACHE",
        266 => "SQL_CALC_FOUND_ROWS",
        267 => "SQL_LOG_BIN",
        268 => "SQL_LOG_OFF",
        269 => "SQL_LOG_UPDATE",
        270 => "SQL_LOW_PRIORITY_UPDATES",
        271 => "SQL_MAX_JOIN_SIZE",
        272 => "SQL_NO_CACHE",
        273 => "SQL_QUOTE_SHOW_CREATE",
        274 => "SQL_SAFE_UPDATES",
        275 => "SQL_SELECT_LIMIT",
        276 => "SQL_SLAVE_SKIP_COUNTER",
        277 => "SQL_SMALL_RESULT",
        278 => "SQL_WARNINGS",
        279 => "START",
        280 => "STARTING",
        281 => "STATUS",
        282 => "STOP",
        283 => "STORAGE",
        284 => "STRAIGHT_JOIN",
        285 => "STRING",
        286 => "STRIPED",
        287 => "SUPER",
        288 => "TABLE",
        289 => "TABLES",
        290 => "TEMPORARY",
        291 => "TERMINATED",
        292 => "THEN",
        293 => "TO",
        294 => "TRAILING",
        295 => "TRANSACTIONAL",
        296 => "TRUE",
        297 => "TRUNCATE",
        298 => "TYPE",
        299 => "TYPES",
        300 => "UNCOMMITTED",
        301 => "UNION",
        302 => "UNION ALL",
        303 => "UNIQUE",
        304 => "UNLOCK",
        305 => "UNSIGNED",
        306 => "UPDATE",
        307 => "USAGE",
        308 => "USE",
        309 => "USING",
        310 => "VALUES",
        311 => "VARIABLES",
        312 => "VIEW",
        313 => "WHEN",
        314 => "WHERE",
        315 => "WITH",
        316 => "WORK",
        317 => "WRITE",
        318 => "XOR",
        319 => "YEAR_MONTH",
        320 => "ABS",
        321 => "ACOS",
        322 => "ADDDATE",
        323 => "ADDTIME",
        324 => "AES_DECRYPT",
        325 => "AES_ENCRYPT",
        326 => "AREA",
        327 => "ASBINARY",
        328 => "ASCII",
        329 => "ASIN",
        330 => "ASTEXT",
        331 => "ATAN",
        332 => "ATAN2",
        333 => "AVG",
        334 => "BDMPOLYFROMTEXT",
        335 => "BDMPOLYFROMWKB",
        336 => "BDPOLYFROMTEXT",
        337 => "BDPOLYFROMWKB",
        338 => "BENCHMARK",
        339 => "BIN",
        340 => "BIT_AND",
        341 => "BIT_COUNT",
        342 => "BIT_LENGTH",
        343 => "BIT_OR",
        344 => "BIT_XOR",
        345 => "BOUNDARY",
        346 => "BUFFER",
        347 => "CAST",
        348 => "CEIL",
        349 => "CEILING",
        350 => "CENTROID",
        351 => "CHAR",
        352 => "CHARACTER_LENGTH",
        353 => "CHARSET",
        354 => "CHAR_LENGTH",
        355 => "COALESCE",
        356 => "COERCIBILITY",
        357 => "COLLATION",
        358 => "COMPRESS",
        359 => "CONCAT",
        360 => "CONCAT_WS",
        361 => "CONNECTION_ID",
        362 => "CONTAINS",
        363 => "CONV",
        364 => "CONVERT",
        365 => "CONVERT_TZ",
        366 => "CONVEXHULL",
        367 => "COS",
        368 => "COT",
        369 => "COUNT",
        370 => "CRC32",
        371 => "CROSSES",
        372 => "CURDATE",
        373 => "CURRENT_DATE",
        374 => "CURRENT_TIME",
        375 => "CURRENT_TIMESTAMP",
        376 => "CURRENT_USER",
        377 => "CURTIME",
        378 => "DATABASE",
        379 => "DATE",
        380 => "DATEDIFF",
        381 => "DATE_ADD",
        382 => "DATE_DIFF",
        383 => "DATE_FORMAT",
        384 => "DATE_SUB",
        385 => "DAY",
        386 => "DAYNAME",
        387 => "DAYOFMONTH",
        388 => "DAYOFWEEK",
        389 => "DAYOFYEAR",
        390 => "DECODE",
        391 => "DEFAULT",
        392 => "DEGREES",
        393 => "DES_DECRYPT",
        394 => "DES_ENCRYPT",
        395 => "DIFFERENCE",
        396 => "DIMENSION",
        397 => "DISJOINT",
        398 => "DISTANCE",
        399 => "ELT",
        400 => "ENCODE",
        401 => "ENCRYPT",
        402 => "ENDPOINT",
        403 => "ENVELOPE",
        404 => "EQUALS",
        405 => "EXP",
        406 => "EXPORT_SET",
        407 => "EXTERIORRING",
        408 => "EXTRACT",
        409 => "EXTRACTVALUE",
        410 => "FIELD",
        411 => "FIND_IN_SET",
        412 => "FLOOR",
        413 => "FORMAT",
        414 => "FOUND_ROWS",
        415 => "FROM_DAYS",
        416 => "FROM_UNIXTIME",
        417 => "GEOMCOLLFROMTEXT",
        418 => "GEOMCOLLFROMWKB",
        419 => "GEOMETRYCOLLECTION",
        420 => "GEOMETRYCOLLECTIONFROMTEXT",
        421 => "GEOMETRYCOLLECTIONFROMWKB",
        422 => "GEOMETRYFROMTEXT",
        423 => "GEOMETRYFROMWKB",
        424 => "GEOMETRYN",
        425 => "GEOMETRYTYPE",
        426 => "GEOMFROMTEXT",
        427 => "GEOMFROMWKB",
        428 => "GET_FORMAT",
        429 => "GET_LOCK",
        430 => "GLENGTH",
        431 => "GREATEST",
        432 => "GROUP_CONCAT",
        433 => "GROUP_UNIQUE_USERS",
        434 => "HEX",
        435 => "HOUR",
        436 => "IF",
        437 => "IFNULL",
        438 => "INET_ATON",
        439 => "INET_NTOA",
        440 => "INSERT",
        441 => "INSTR",
        442 => "INTERIORRINGN",
        443 => "INTERSECTION",
        444 => "INTERSECTS",
        445 => "INTERVAL",
        446 => "ISCLOSED",
        447 => "ISEMPTY",
        448 => "ISNULL",
        449 => "ISRING",
        450 => "ISSIMPLE",
        451 => "IS_FREE_LOCK",
        452 => "IS_USED_LOCK",
        453 => "LAST_DAY",
        454 => "LAST_INSERT_ID",
        455 => "LCASE",
        456 => "LEAST",
        457 => "LEFT",
        458 => "LENGTH",
        459 => "LINEFROMTEXT",
        460 => "LINEFROMWKB",
        461 => "LINESTRING",
        462 => "LINESTRINGFROMTEXT",
        463 => "LINESTRINGFROMWKB",
        464 => "LN",
        465 => "LOAD_FILE",
        466 => "LOCALTIME",
        467 => "LOCALTIMESTAMP",
        468 => "LOCATE",
        469 => "LOG",
        470 => "LOG10",
        471 => "LOG2",
        472 => "LOWER",
        473 => "LPAD",
        474 => "LTRIM",
        475 => "MAKEDATE",
        476 => "MAKETIME",
        477 => "MAKE_SET",
        478 => "MASTER_POS_WAIT",
        479 => "MAX",
        480 => "MBRCONTAINS",
        481 => "MBRDISJOINT",
        482 => "MBREQUAL",
        483 => "MBRINTERSECTS",
        484 => "MBROVERLAPS",
        485 => "MBRTOUCHES",
        486 => "MBRWITHIN",
        487 => "MD5",
        488 => "MICROSECOND",
        489 => "MID",
        490 => "MIN",
        491 => "MINUTE",
        492 => "MLINEFROMTEXT",
        493 => "MLINEFROMWKB",
        494 => "MOD",
        495 => "MONTH",
        496 => "MONTHNAME",
        497 => "MPOINTFROMTEXT",
        498 => "MPOINTFROMWKB",
        499 => "MPOLYFROMTEXT",
        500 => "MPOLYFROMWKB",
        501 => "MULTILINESTRING",
        502 => "MULTILINESTRINGFROMTEXT",
        503 => "MULTILINESTRINGFROMWKB",
        504 => "MULTIPOINT",
        505 => "MULTIPOINTFROMTEXT",
        506 => "MULTIPOINTFROMWKB",
        507 => "MULTIPOLYGON",
        508 => "MULTIPOLYGONFROMTEXT",
        509 => "MULTIPOLYGONFROMWKB",
        510 => "NAME_CONST",
        511 => "NULLIF",
        512 => "NUMGEOMETRIES",
        513 => "NUMINTERIORRINGS",
        514 => "NUMPOINTS",
        515 => "OCT",
        516 => "OCTET_LENGTH",
        517 => "OLD_PASSWORD",
        518 => "ORD",
        519 => "OVERLAPS",
        520 => "PASSWORD",
        521 => "PERIOD_ADD",
        522 => "PERIOD_DIFF",
        523 => "PI",
        524 => "POINT",
        525 => "POINTFROMTEXT",
        526 => "POINTFROMWKB",
        527 => "POINTN",
        528 => "POINTONSURFACE",
        529 => "POLYFROMTEXT",
        530 => "POLYFROMWKB",
        531 => "POLYGON",
        532 => "POLYGONFROMTEXT",
        533 => "POLYGONFROMWKB",
        534 => "POSITION",
        535 => "POW",
        536 => "POWER",
        537 => "QUARTER",
        538 => "QUOTE",
        539 => "RADIANS",
        540 => "RAND",
        541 => "RELATED",
        542 => "RELEASE_LOCK",
        543 => "REPEAT",
        544 => "REPLACE",
        545 => "REVERSE",
        546 => "RIGHT",
        547 => "ROUND",
        548 => "ROW_COUNT",
        549 => "RPAD",
        550 => "RTRIM",
        551 => "SCHEMA",
        552 => "SECOND",
        553 => "SEC_TO_TIME",
        554 => "SESSION_USER",
        555 => "SHA",
        556 => "SHA1",
        557 => "SIGN",
        558 => "SIN",
        559 => "SLEEP",
        560 => "SOUNDEX",
        561 => "SPACE",
        562 => "SQRT",
        563 => "SRID",
        564 => "STARTPOINT",
        565 => "STD",
        566 => "STDDEV",
        567 => "STDDEV_POP",
        568 => "STDDEV_SAMP",
        569 => "STRCMP",
        570 => "STR_TO_DATE",
        571 => "SUBDATE",
        572 => "SUBSTR",
        573 => "SUBSTRING",
        574 => "SUBSTRING_INDEX",
        575 => "SUBTIME",
        576 => "SUM",
        577 => "SYMDIFFERENCE",
        578 => "SYSDATE",
        579 => "SYSTEM_USER",
        580 => "TAN",
        581 => "TIME",
        582 => "TIMEDIFF",
        583 => "TIMESTAMP",
        584 => "TIMESTAMPADD",
        585 => "TIMESTAMPDIFF",
        586 => "TIME_FORMAT",
        587 => "TIME_TO_SEC",
        588 => "TOUCHES",
        589 => "TO_DAYS",
        590 => "TRIM",
        591 => "TRUNCATE",
        592 => "UCASE",
        593 => "UNCOMPRESS",
        594 => "UNCOMPRESSED_LENGTH",
        595 => "UNHEX",
        596 => "UNIQUE_USERS",
        597 => "UNIX_TIMESTAMP",
        598 => "UPDATEXML",
        599 => "UPPER",
        600 => "USER",
        601 => "UTC_DATE",
        602 => "UTC_TIME",
        603 => "UTC_TIMESTAMP",
        604 => "UUID",
        605 => "VARIANCE",
        606 => "VAR_POP",
        607 => "VAR_SAMP",
        608 => "VERSION",
        609 => "WEEK",
        610 => "WEEKDAY",
        611 => "WEEKOFYEAR",
        612 => "WITHIN",
        613 => "X",
        614 => "Y",
        615 => "YEAR",
        616 => "YEARWEEK",
    ]);
}

if (!defined("ryunosuke\\Functions\\Package\\JSON_MAX_DEPTH")) {
    /** json_*** 関数で $depth 引数を表す定数 */
    define("ryunosuke\\Functions\\Package\\JSON_MAX_DEPTH", -1);
}

if (!defined("ryunosuke\\Functions\\Package\\TOKEN_NAME")) {
    /** parse_php 関数でトークン名変換をするか */
    define("ryunosuke\\Functions\\Package\\TOKEN_NAME", 2);
}

if (!defined("ryunosuke\\Functions\\Package\\SI_UNITS")) {
    /** SI 接頭辞 */
    define("ryunosuke\\Functions\\Package\\SI_UNITS", [
        -8 => ["y"],
        -7 => ["z"],
        -6 => ["a"],
        -5 => ["f"],
        -4 => ["p"],
        -3 => ["n"],
        -2 => ["u", "μ", "µ"],
        -1 => ["m"],
        0  => [],
        1  => ["k", "K"],
        2  => ["M"],
        3  => ["G"],
        4  => ["T"],
        5  => ["P"],
        6  => ["E"],
        7  => ["Z"],
        8  => ["Y"],
    ]);
}

if (!defined("ryunosuke\\Functions\\Package\\SORT_STRICT")) {
    /** SORT_XXX 定数の厳密版 */
    define("ryunosuke\\Functions\\Package\\SORT_STRICT", 256);
}


# functions
define("ryunosuke\\Functions\\Package\\arrays", ["ryunosuke\\Functions\\Package\\Arrays", "arrays"]);
define("ryunosuke\\Functions\\Package\\arrayize", ["ryunosuke\\Functions\\Package\\Arrays", "arrayize"]);
define("ryunosuke\\Functions\\Package\\is_indexarray", ["ryunosuke\\Functions\\Package\\Arrays", "is_indexarray"]);
define("ryunosuke\\Functions\\Package\\is_hasharray", ["ryunosuke\\Functions\\Package\\Arrays", "is_hasharray"]);
define("ryunosuke\\Functions\\Package\\first_key", ["ryunosuke\\Functions\\Package\\Arrays", "first_key"]);
define("ryunosuke\\Functions\\Package\\first_value", ["ryunosuke\\Functions\\Package\\Arrays", "first_value"]);
define("ryunosuke\\Functions\\Package\\first_keyvalue", ["ryunosuke\\Functions\\Package\\Arrays", "first_keyvalue"]);
define("ryunosuke\\Functions\\Package\\last_key", ["ryunosuke\\Functions\\Package\\Arrays", "last_key"]);
define("ryunosuke\\Functions\\Package\\last_value", ["ryunosuke\\Functions\\Package\\Arrays", "last_value"]);
define("ryunosuke\\Functions\\Package\\last_keyvalue", ["ryunosuke\\Functions\\Package\\Arrays", "last_keyvalue"]);
define("ryunosuke\\Functions\\Package\\prev_key", ["ryunosuke\\Functions\\Package\\Arrays", "prev_key"]);
define("ryunosuke\\Functions\\Package\\next_key", ["ryunosuke\\Functions\\Package\\Arrays", "next_key"]);
define("ryunosuke\\Functions\\Package\\in_array_and", ["ryunosuke\\Functions\\Package\\Arrays", "in_array_and"]);
define("ryunosuke\\Functions\\Package\\in_array_or", ["ryunosuke\\Functions\\Package\\Arrays", "in_array_or"]);
define("ryunosuke\\Functions\\Package\\kvsort", ["ryunosuke\\Functions\\Package\\Arrays", "kvsort"]);
define("ryunosuke\\Functions\\Package\\array_add", ["ryunosuke\\Functions\\Package\\Arrays", "array_add"]);
define("ryunosuke\\Functions\\Package\\array_merge2", ["ryunosuke\\Functions\\Package\\Arrays", "array_merge2"]);
define("ryunosuke\\Functions\\Package\\array_mix", ["ryunosuke\\Functions\\Package\\Arrays", "array_mix"]);
define("ryunosuke\\Functions\\Package\\array_zip", ["ryunosuke\\Functions\\Package\\Arrays", "array_zip"]);
define("ryunosuke\\Functions\\Package\\array_cross", ["ryunosuke\\Functions\\Package\\Arrays", "array_cross"]);
define("ryunosuke\\Functions\\Package\\array_implode", ["ryunosuke\\Functions\\Package\\Arrays", "array_implode"]);
define("ryunosuke\\Functions\\Package\\array_explode", ["ryunosuke\\Functions\\Package\\Arrays", "array_explode"]);
define("ryunosuke\\Functions\\Package\\array_sprintf", ["ryunosuke\\Functions\\Package\\Arrays", "array_sprintf"]);
define("ryunosuke\\Functions\\Package\\array_strpad", ["ryunosuke\\Functions\\Package\\Arrays", "array_strpad"]);
define("ryunosuke\\Functions\\Package\\array_pos", ["ryunosuke\\Functions\\Package\\Arrays", "array_pos"]);
define("ryunosuke\\Functions\\Package\\array_pos_key", ["ryunosuke\\Functions\\Package\\Arrays", "array_pos_key"]);
define("ryunosuke\\Functions\\Package\\array_of", ["ryunosuke\\Functions\\Package\\Arrays", "array_of"]);
define("ryunosuke\\Functions\\Package\\array_get", ["ryunosuke\\Functions\\Package\\Arrays", "array_get"]);
define("ryunosuke\\Functions\\Package\\array_set", ["ryunosuke\\Functions\\Package\\Arrays", "array_set"]);
define("ryunosuke\\Functions\\Package\\array_put", ["ryunosuke\\Functions\\Package\\Arrays", "array_put"]);
define("ryunosuke\\Functions\\Package\\array_unset", ["ryunosuke\\Functions\\Package\\Arrays", "array_unset"]);
define("ryunosuke\\Functions\\Package\\array_dive", ["ryunosuke\\Functions\\Package\\Arrays", "array_dive"]);
define("ryunosuke\\Functions\\Package\\array_keys_exist", ["ryunosuke\\Functions\\Package\\Arrays", "array_keys_exist"]);
define("ryunosuke\\Functions\\Package\\array_find", ["ryunosuke\\Functions\\Package\\Arrays", "array_find"]);
define("ryunosuke\\Functions\\Package\\array_rekey", ["ryunosuke\\Functions\\Package\\Arrays", "array_rekey"]);
define("ryunosuke\\Functions\\Package\\array_grep_key", ["ryunosuke\\Functions\\Package\\Arrays", "array_grep_key"]);
define("ryunosuke\\Functions\\Package\\array_map_recursive", ["ryunosuke\\Functions\\Package\\Arrays", "array_map_recursive"]);
define("ryunosuke\\Functions\\Package\\array_map_key", ["ryunosuke\\Functions\\Package\\Arrays", "array_map_key"]);
define("ryunosuke\\Functions\\Package\\array_filter_key", ["ryunosuke\\Functions\\Package\\Arrays", "array_filter_key"]);
define("ryunosuke\\Functions\\Package\\array_where", ["ryunosuke\\Functions\\Package\\Arrays", "array_where"]);
define("ryunosuke\\Functions\\Package\\array_map_filter", ["ryunosuke\\Functions\\Package\\Arrays", "array_map_filter"]);
define("ryunosuke\\Functions\\Package\\array_map_method", ["ryunosuke\\Functions\\Package\\Arrays", "array_map_method"]);
define("ryunosuke\\Functions\\Package\\array_maps", ["ryunosuke\\Functions\\Package\\Arrays", "array_maps"]);
define("ryunosuke\\Functions\\Package\\array_kvmap", ["ryunosuke\\Functions\\Package\\Arrays", "array_kvmap"]);
define("ryunosuke\\Functions\\Package\\array_kmap", ["ryunosuke\\Functions\\Package\\Arrays", "array_kmap"]);
define("ryunosuke\\Functions\\Package\\array_nmap", ["ryunosuke\\Functions\\Package\\Arrays", "array_nmap"]);
define("ryunosuke\\Functions\\Package\\array_lmap", ["ryunosuke\\Functions\\Package\\Arrays", "array_lmap"]);
define("ryunosuke\\Functions\\Package\\array_rmap", ["ryunosuke\\Functions\\Package\\Arrays", "array_rmap"]);
define("ryunosuke\\Functions\\Package\\array_each", ["ryunosuke\\Functions\\Package\\Arrays", "array_each"]);
define("ryunosuke\\Functions\\Package\\array_depth", ["ryunosuke\\Functions\\Package\\Arrays", "array_depth"]);
define("ryunosuke\\Functions\\Package\\array_insert", ["ryunosuke\\Functions\\Package\\Arrays", "array_insert"]);
define("ryunosuke\\Functions\\Package\\array_assort", ["ryunosuke\\Functions\\Package\\Arrays", "array_assort"]);
define("ryunosuke\\Functions\\Package\\array_count", ["ryunosuke\\Functions\\Package\\Arrays", "array_count"]);
define("ryunosuke\\Functions\\Package\\array_group", ["ryunosuke\\Functions\\Package\\Arrays", "array_group"]);
define("ryunosuke\\Functions\\Package\\array_aggregate", ["ryunosuke\\Functions\\Package\\Arrays", "array_aggregate"]);
define("ryunosuke\\Functions\\Package\\array_all", ["ryunosuke\\Functions\\Package\\Arrays", "array_all"]);
define("ryunosuke\\Functions\\Package\\array_any", ["ryunosuke\\Functions\\Package\\Arrays", "array_any"]);
define("ryunosuke\\Functions\\Package\\array_distinct", ["ryunosuke\\Functions\\Package\\Arrays", "array_distinct"]);
define("ryunosuke\\Functions\\Package\\array_order", ["ryunosuke\\Functions\\Package\\Arrays", "array_order"]);
define("ryunosuke\\Functions\\Package\\array_shuffle", ["ryunosuke\\Functions\\Package\\Arrays", "array_shuffle"]);
define("ryunosuke\\Functions\\Package\\array_shrink_key", ["ryunosuke\\Functions\\Package\\Arrays", "array_shrink_key"]);
define("ryunosuke\\Functions\\Package\\array_fill_gap", ["ryunosuke\\Functions\\Package\\Arrays", "array_fill_gap"]);
define("ryunosuke\\Functions\\Package\\array_fill_callback", ["ryunosuke\\Functions\\Package\\Arrays", "array_fill_callback"]);
define("ryunosuke\\Functions\\Package\\array_pickup", ["ryunosuke\\Functions\\Package\\Arrays", "array_pickup"]);
define("ryunosuke\\Functions\\Package\\array_remove", ["ryunosuke\\Functions\\Package\\Arrays", "array_remove"]);
define("ryunosuke\\Functions\\Package\\array_lookup", ["ryunosuke\\Functions\\Package\\Arrays", "array_lookup"]);
define("ryunosuke\\Functions\\Package\\array_select", ["ryunosuke\\Functions\\Package\\Arrays", "array_select"]);
define("ryunosuke\\Functions\\Package\\array_columns", ["ryunosuke\\Functions\\Package\\Arrays", "array_columns"]);
define("ryunosuke\\Functions\\Package\\array_uncolumns", ["ryunosuke\\Functions\\Package\\Arrays", "array_uncolumns"]);
define("ryunosuke\\Functions\\Package\\array_convert", ["ryunosuke\\Functions\\Package\\Arrays", "array_convert"]);
define("ryunosuke\\Functions\\Package\\array_flatten", ["ryunosuke\\Functions\\Package\\Arrays", "array_flatten"]);
define("ryunosuke\\Functions\\Package\\array_nest", ["ryunosuke\\Functions\\Package\\Arrays", "array_nest"]);
define("ryunosuke\\Functions\\Package\\array_difference", ["ryunosuke\\Functions\\Package\\Arrays", "array_difference"]);
define("ryunosuke\\Functions\\Package\\stdclass", ["ryunosuke\\Functions\\Package\\Classobj", "stdclass"]);
define("ryunosuke\\Functions\\Package\\detect_namespace", ["ryunosuke\\Functions\\Package\\Classobj", "detect_namespace"]);
define("ryunosuke\\Functions\\Package\\class_uses_all", ["ryunosuke\\Functions\\Package\\Classobj", "class_uses_all"]);
define("ryunosuke\\Functions\\Package\\class_loader", ["ryunosuke\\Functions\\Package\\Classobj", "class_loader"]);
define("ryunosuke\\Functions\\Package\\class_namespace", ["ryunosuke\\Functions\\Package\\Classobj", "class_namespace"]);
define("ryunosuke\\Functions\\Package\\class_shorten", ["ryunosuke\\Functions\\Package\\Classobj", "class_shorten"]);
define("ryunosuke\\Functions\\Package\\class_replace", ["ryunosuke\\Functions\\Package\\Classobj", "class_replace"]);
define("ryunosuke\\Functions\\Package\\class_extends", ["ryunosuke\\Functions\\Package\\Classobj", "class_extends"]);
define("ryunosuke\\Functions\\Package\\const_exists", ["ryunosuke\\Functions\\Package\\Classobj", "const_exists"]);
define("ryunosuke\\Functions\\Package\\object_dive", ["ryunosuke\\Functions\\Package\\Classobj", "object_dive"]);
define("ryunosuke\\Functions\\Package\\get_class_constants", ["ryunosuke\\Functions\\Package\\Classobj", "get_class_constants"]);
define("ryunosuke\\Functions\\Package\\get_object_properties", ["ryunosuke\\Functions\\Package\\Classobj", "get_object_properties"]);
define("ryunosuke\\Functions\\Package\\date_timestamp", ["ryunosuke\\Functions\\Package\\Date", "date_timestamp"]);
define("ryunosuke\\Functions\\Package\\date_convert", ["ryunosuke\\Functions\\Package\\Date", "date_convert"]);
define("ryunosuke\\Functions\\Package\\date_fromto", ["ryunosuke\\Functions\\Package\\Date", "date_fromto"]);
define("ryunosuke\\Functions\\Package\\date_interval", ["ryunosuke\\Functions\\Package\\Date", "date_interval"]);
define("ryunosuke\\Functions\\Package\\file_list", ["ryunosuke\\Functions\\Package\\FileSystem", "file_list"]);
define("ryunosuke\\Functions\\Package\\file_tree", ["ryunosuke\\Functions\\Package\\FileSystem", "file_tree"]);
define("ryunosuke\\Functions\\Package\\file_suffix", ["ryunosuke\\Functions\\Package\\FileSystem", "file_suffix"]);
define("ryunosuke\\Functions\\Package\\file_extension", ["ryunosuke\\Functions\\Package\\FileSystem", "file_extension"]);
define("ryunosuke\\Functions\\Package\\file_set_contents", ["ryunosuke\\Functions\\Package\\FileSystem", "file_set_contents"]);
define("ryunosuke\\Functions\\Package\\file_rewrite_contents", ["ryunosuke\\Functions\\Package\\FileSystem", "file_rewrite_contents"]);
define("ryunosuke\\Functions\\Package\\file_pos", ["ryunosuke\\Functions\\Package\\FileSystem", "file_pos"]);
define("ryunosuke\\Functions\\Package\\file_mimetype", ["ryunosuke\\Functions\\Package\\FileSystem", "file_mimetype"]);
define("ryunosuke\\Functions\\Package\\mkdir_p", ["ryunosuke\\Functions\\Package\\FileSystem", "mkdir_p"]);
define("ryunosuke\\Functions\\Package\\dirname_r", ["ryunosuke\\Functions\\Package\\FileSystem", "dirname_r"]);
define("ryunosuke\\Functions\\Package\\dirmtime", ["ryunosuke\\Functions\\Package\\FileSystem", "dirmtime"]);
define("ryunosuke\\Functions\\Package\\fnmatch_and", ["ryunosuke\\Functions\\Package\\FileSystem", "fnmatch_and"]);
define("ryunosuke\\Functions\\Package\\fnmatch_or", ["ryunosuke\\Functions\\Package\\FileSystem", "fnmatch_or"]);
define("ryunosuke\\Functions\\Package\\path_is_absolute", ["ryunosuke\\Functions\\Package\\FileSystem", "path_is_absolute"]);
define("ryunosuke\\Functions\\Package\\path_resolve", ["ryunosuke\\Functions\\Package\\FileSystem", "path_resolve"]);
define("ryunosuke\\Functions\\Package\\path_relative", ["ryunosuke\\Functions\\Package\\FileSystem", "path_relative"]);
define("ryunosuke\\Functions\\Package\\path_normalize", ["ryunosuke\\Functions\\Package\\FileSystem", "path_normalize"]);
define("ryunosuke\\Functions\\Package\\cp_rf", ["ryunosuke\\Functions\\Package\\FileSystem", "cp_rf"]);
define("ryunosuke\\Functions\\Package\\rm_rf", ["ryunosuke\\Functions\\Package\\FileSystem", "rm_rf"]);
define("ryunosuke\\Functions\\Package\\tmpname", ["ryunosuke\\Functions\\Package\\FileSystem", "tmpname"]);
define("ryunosuke\\Functions\\Package\\memory_path", ["ryunosuke\\Functions\\Package\\FileSystem", "memory_path"]);
define("ryunosuke\\Functions\\Package\\delegate", ["ryunosuke\\Functions\\Package\\Funchand", "delegate"]);
define("ryunosuke\\Functions\\Package\\abind", ["ryunosuke\\Functions\\Package\\Funchand", "abind"]);
define("ryunosuke\\Functions\\Package\\nbind", ["ryunosuke\\Functions\\Package\\Funchand", "nbind"]);
define("ryunosuke\\Functions\\Package\\lbind", ["ryunosuke\\Functions\\Package\\Funchand", "lbind"]);
define("ryunosuke\\Functions\\Package\\rbind", ["ryunosuke\\Functions\\Package\\Funchand", "rbind"]);
define("ryunosuke\\Functions\\Package\\ope_func", ["ryunosuke\\Functions\\Package\\Funchand", "ope_func"]);
define("ryunosuke\\Functions\\Package\\not_func", ["ryunosuke\\Functions\\Package\\Funchand", "not_func"]);
define("ryunosuke\\Functions\\Package\\eval_func", ["ryunosuke\\Functions\\Package\\Funchand", "eval_func"]);
define("ryunosuke\\Functions\\Package\\reflect_callable", ["ryunosuke\\Functions\\Package\\Funchand", "reflect_callable"]);
define("ryunosuke\\Functions\\Package\\callable_code", ["ryunosuke\\Functions\\Package\\Funchand", "callable_code"]);
define("ryunosuke\\Functions\\Package\\call_safely", ["ryunosuke\\Functions\\Package\\Funchand", "call_safely"]);
define("ryunosuke\\Functions\\Package\\ob_capture", ["ryunosuke\\Functions\\Package\\Funchand", "ob_capture"]);
define("ryunosuke\\Functions\\Package\\is_bindable_closure", ["ryunosuke\\Functions\\Package\\Funchand", "is_bindable_closure"]);
define("ryunosuke\\Functions\\Package\\by_builtin", ["ryunosuke\\Functions\\Package\\Funchand", "by_builtin"]);
define("ryunosuke\\Functions\\Package\\namedcallize", ["ryunosuke\\Functions\\Package\\Funchand", "namedcallize"]);
define("ryunosuke\\Functions\\Package\\parameter_length", ["ryunosuke\\Functions\\Package\\Funchand", "parameter_length"]);
define("ryunosuke\\Functions\\Package\\parameter_default", ["ryunosuke\\Functions\\Package\\Funchand", "parameter_default"]);
define("ryunosuke\\Functions\\Package\\parameter_wiring", ["ryunosuke\\Functions\\Package\\Funchand", "parameter_wiring"]);
define("ryunosuke\\Functions\\Package\\function_shorten", ["ryunosuke\\Functions\\Package\\Funchand", "function_shorten"]);
define("ryunosuke\\Functions\\Package\\func_user_func_array", ["ryunosuke\\Functions\\Package\\Funchand", "func_user_func_array"]);
define("ryunosuke\\Functions\\Package\\func_wiring", ["ryunosuke\\Functions\\Package\\Funchand", "func_wiring"]);
define("ryunosuke\\Functions\\Package\\func_new", ["ryunosuke\\Functions\\Package\\Funchand", "func_new"]);
define("ryunosuke\\Functions\\Package\\func_method", ["ryunosuke\\Functions\\Package\\Funchand", "func_method"]);
define("ryunosuke\\Functions\\Package\\function_alias", ["ryunosuke\\Functions\\Package\\Funchand", "function_alias"]);
define("ryunosuke\\Functions\\Package\\function_parameter", ["ryunosuke\\Functions\\Package\\Funchand", "function_parameter"]);
define("ryunosuke\\Functions\\Package\\minimum", ["ryunosuke\\Functions\\Package\\Math", "minimum"]);
define("ryunosuke\\Functions\\Package\\maximum", ["ryunosuke\\Functions\\Package\\Math", "maximum"]);
define("ryunosuke\\Functions\\Package\\mode", ["ryunosuke\\Functions\\Package\\Math", "mode"]);
define("ryunosuke\\Functions\\Package\\mean", ["ryunosuke\\Functions\\Package\\Math", "mean"]);
define("ryunosuke\\Functions\\Package\\median", ["ryunosuke\\Functions\\Package\\Math", "median"]);
define("ryunosuke\\Functions\\Package\\average", ["ryunosuke\\Functions\\Package\\Math", "average"]);
define("ryunosuke\\Functions\\Package\\sum", ["ryunosuke\\Functions\\Package\\Math", "sum"]);
define("ryunosuke\\Functions\\Package\\clamp", ["ryunosuke\\Functions\\Package\\Math", "clamp"]);
define("ryunosuke\\Functions\\Package\\random_at", ["ryunosuke\\Functions\\Package\\Math", "random_at"]);
define("ryunosuke\\Functions\\Package\\probability", ["ryunosuke\\Functions\\Package\\Math", "probability"]);
define("ryunosuke\\Functions\\Package\\normal_rand", ["ryunosuke\\Functions\\Package\\Math", "normal_rand"]);
define("ryunosuke\\Functions\\Package\\getipaddress", ["ryunosuke\\Functions\\Package\\Network", "getipaddress"]);
define("ryunosuke\\Functions\\Package\\incidr", ["ryunosuke\\Functions\\Package\\Network", "incidr"]);
define("ryunosuke\\Functions\\Package\\ping", ["ryunosuke\\Functions\\Package\\Network", "ping"]);
define("ryunosuke\\Functions\\Package\\http_requests", ["ryunosuke\\Functions\\Package\\Network", "http_requests"]);
define("ryunosuke\\Functions\\Package\\http_request", ["ryunosuke\\Functions\\Package\\Network", "http_request"]);
define("ryunosuke\\Functions\\Package\\http_head", ["ryunosuke\\Functions\\Package\\Network", "http_head"]);
define("ryunosuke\\Functions\\Package\\http_get", ["ryunosuke\\Functions\\Package\\Network", "http_get"]);
define("ryunosuke\\Functions\\Package\\http_post", ["ryunosuke\\Functions\\Package\\Network", "http_post"]);
define("ryunosuke\\Functions\\Package\\http_put", ["ryunosuke\\Functions\\Package\\Network", "http_put"]);
define("ryunosuke\\Functions\\Package\\http_patch", ["ryunosuke\\Functions\\Package\\Network", "http_patch"]);
define("ryunosuke\\Functions\\Package\\http_delete", ["ryunosuke\\Functions\\Package\\Network", "http_delete"]);
define("ryunosuke\\Functions\\Package\\sql_quote", ["ryunosuke\\Functions\\Package\\Sql", "sql_quote"]);
define("ryunosuke\\Functions\\Package\\sql_bind", ["ryunosuke\\Functions\\Package\\Sql", "sql_bind"]);
define("ryunosuke\\Functions\\Package\\sql_format", ["ryunosuke\\Functions\\Package\\Sql", "sql_format"]);
define("ryunosuke\\Functions\\Package\\strcat", ["ryunosuke\\Functions\\Package\\Strings", "strcat"]);
define("ryunosuke\\Functions\\Package\\concat", ["ryunosuke\\Functions\\Package\\Strings", "concat"]);
define("ryunosuke\\Functions\\Package\\split_noempty", ["ryunosuke\\Functions\\Package\\Strings", "split_noempty"]);
define("ryunosuke\\Functions\\Package\\multiexplode", ["ryunosuke\\Functions\\Package\\Strings", "multiexplode"]);
define("ryunosuke\\Functions\\Package\\quoteexplode", ["ryunosuke\\Functions\\Package\\Strings", "quoteexplode"]);
define("ryunosuke\\Functions\\Package\\strrstr", ["ryunosuke\\Functions\\Package\\Strings", "strrstr"]);
define("ryunosuke\\Functions\\Package\\strpos_array", ["ryunosuke\\Functions\\Package\\Strings", "strpos_array"]);
define("ryunosuke\\Functions\\Package\\strpos_quoted", ["ryunosuke\\Functions\\Package\\Strings", "strpos_quoted"]);
define("ryunosuke\\Functions\\Package\\str_chunk", ["ryunosuke\\Functions\\Package\\Strings", "str_chunk"]);
define("ryunosuke\\Functions\\Package\\str_anyof", ["ryunosuke\\Functions\\Package\\Strings", "str_anyof"]);
define("ryunosuke\\Functions\\Package\\str_equals", ["ryunosuke\\Functions\\Package\\Strings", "str_equals"]);
define("ryunosuke\\Functions\\Package\\str_contains", ["ryunosuke\\Functions\\Package\\Strings", "str_contains"]);
define("ryunosuke\\Functions\\Package\\str_chop", ["ryunosuke\\Functions\\Package\\Strings", "str_chop"]);
define("ryunosuke\\Functions\\Package\\str_lchop", ["ryunosuke\\Functions\\Package\\Strings", "str_lchop"]);
define("ryunosuke\\Functions\\Package\\str_rchop", ["ryunosuke\\Functions\\Package\\Strings", "str_rchop"]);
define("ryunosuke\\Functions\\Package\\str_putcsv", ["ryunosuke\\Functions\\Package\\Strings", "str_putcsv"]);
define("ryunosuke\\Functions\\Package\\str_subreplace", ["ryunosuke\\Functions\\Package\\Strings", "str_subreplace"]);
define("ryunosuke\\Functions\\Package\\str_submap", ["ryunosuke\\Functions\\Package\\Strings", "str_submap"]);
define("ryunosuke\\Functions\\Package\\str_embed", ["ryunosuke\\Functions\\Package\\Strings", "str_embed"]);
define("ryunosuke\\Functions\\Package\\str_between", ["ryunosuke\\Functions\\Package\\Strings", "str_between"]);
define("ryunosuke\\Functions\\Package\\str_ellipsis", ["ryunosuke\\Functions\\Package\\Strings", "str_ellipsis"]);
define("ryunosuke\\Functions\\Package\\str_diff", ["ryunosuke\\Functions\\Package\\Strings", "str_diff"]);
define("ryunosuke\\Functions\\Package\\starts_with", ["ryunosuke\\Functions\\Package\\Strings", "starts_with"]);
define("ryunosuke\\Functions\\Package\\ends_with", ["ryunosuke\\Functions\\Package\\Strings", "ends_with"]);
define("ryunosuke\\Functions\\Package\\camel_case", ["ryunosuke\\Functions\\Package\\Strings", "camel_case"]);
define("ryunosuke\\Functions\\Package\\pascal_case", ["ryunosuke\\Functions\\Package\\Strings", "pascal_case"]);
define("ryunosuke\\Functions\\Package\\snake_case", ["ryunosuke\\Functions\\Package\\Strings", "snake_case"]);
define("ryunosuke\\Functions\\Package\\chain_case", ["ryunosuke\\Functions\\Package\\Strings", "chain_case"]);
define("ryunosuke\\Functions\\Package\\namespace_split", ["ryunosuke\\Functions\\Package\\Strings", "namespace_split"]);
define("ryunosuke\\Functions\\Package\\htmltag", ["ryunosuke\\Functions\\Package\\Strings", "htmltag"]);
define("ryunosuke\\Functions\\Package\\css_selector", ["ryunosuke\\Functions\\Package\\Strings", "css_selector"]);
define("ryunosuke\\Functions\\Package\\build_uri", ["ryunosuke\\Functions\\Package\\Strings", "build_uri"]);
define("ryunosuke\\Functions\\Package\\parse_uri", ["ryunosuke\\Functions\\Package\\Strings", "parse_uri"]);
define("ryunosuke\\Functions\\Package\\ini_export", ["ryunosuke\\Functions\\Package\\Strings", "ini_export"]);
define("ryunosuke\\Functions\\Package\\ini_import", ["ryunosuke\\Functions\\Package\\Strings", "ini_import"]);
define("ryunosuke\\Functions\\Package\\csv_export", ["ryunosuke\\Functions\\Package\\Strings", "csv_export"]);
define("ryunosuke\\Functions\\Package\\csv_import", ["ryunosuke\\Functions\\Package\\Strings", "csv_import"]);
define("ryunosuke\\Functions\\Package\\json_export", ["ryunosuke\\Functions\\Package\\Strings", "json_export"]);
define("ryunosuke\\Functions\\Package\\json_import", ["ryunosuke\\Functions\\Package\\Strings", "json_import"]);
define("ryunosuke\\Functions\\Package\\paml_export", ["ryunosuke\\Functions\\Package\\Strings", "paml_export"]);
define("ryunosuke\\Functions\\Package\\paml_import", ["ryunosuke\\Functions\\Package\\Strings", "paml_import"]);
define("ryunosuke\\Functions\\Package\\ltsv_export", ["ryunosuke\\Functions\\Package\\Strings", "ltsv_export"]);
define("ryunosuke\\Functions\\Package\\ltsv_import", ["ryunosuke\\Functions\\Package\\Strings", "ltsv_import"]);
define("ryunosuke\\Functions\\Package\\markdown_table", ["ryunosuke\\Functions\\Package\\Strings", "markdown_table"]);
define("ryunosuke\\Functions\\Package\\markdown_list", ["ryunosuke\\Functions\\Package\\Strings", "markdown_list"]);
define("ryunosuke\\Functions\\Package\\random_string", ["ryunosuke\\Functions\\Package\\Strings", "random_string"]);
define("ryunosuke\\Functions\\Package\\kvsprintf", ["ryunosuke\\Functions\\Package\\Strings", "kvsprintf"]);
define("ryunosuke\\Functions\\Package\\preg_matches", ["ryunosuke\\Functions\\Package\\Strings", "preg_matches"]);
define("ryunosuke\\Functions\\Package\\preg_capture", ["ryunosuke\\Functions\\Package\\Strings", "preg_capture"]);
define("ryunosuke\\Functions\\Package\\preg_splice", ["ryunosuke\\Functions\\Package\\Strings", "preg_splice"]);
define("ryunosuke\\Functions\\Package\\preg_replaces", ["ryunosuke\\Functions\\Package\\Strings", "preg_replaces"]);
define("ryunosuke\\Functions\\Package\\damerau_levenshtein", ["ryunosuke\\Functions\\Package\\Strings", "damerau_levenshtein"]);
define("ryunosuke\\Functions\\Package\\ngram", ["ryunosuke\\Functions\\Package\\Strings", "ngram"]);
define("ryunosuke\\Functions\\Package\\str_guess", ["ryunosuke\\Functions\\Package\\Strings", "str_guess"]);
define("ryunosuke\\Functions\\Package\\str_array", ["ryunosuke\\Functions\\Package\\Strings", "str_array"]);
define("ryunosuke\\Functions\\Package\\mb_substr_replace", ["ryunosuke\\Functions\\Package\\Strings", "mb_substr_replace"]);
define("ryunosuke\\Functions\\Package\\mb_trim", ["ryunosuke\\Functions\\Package\\Strings", "mb_trim"]);
define("ryunosuke\\Functions\\Package\\render_string", ["ryunosuke\\Functions\\Package\\Strings", "render_string"]);
define("ryunosuke\\Functions\\Package\\render_file", ["ryunosuke\\Functions\\Package\\Strings", "render_file"]);
define("ryunosuke\\Functions\\Package\\ob_include", ["ryunosuke\\Functions\\Package\\Strings", "ob_include"]);
define("ryunosuke\\Functions\\Package\\include_string", ["ryunosuke\\Functions\\Package\\Strings", "include_string"]);
define("ryunosuke\\Functions\\Package\\evaluate", ["ryunosuke\\Functions\\Package\\Syntax", "evaluate"]);
define("ryunosuke\\Functions\\Package\\parse_php", ["ryunosuke\\Functions\\Package\\Syntax", "parse_php"]);
define("ryunosuke\\Functions\\Package\\indent_php", ["ryunosuke\\Functions\\Package\\Syntax", "indent_php"]);
define("ryunosuke\\Functions\\Package\\highlight_php", ["ryunosuke\\Functions\\Package\\Syntax", "highlight_php"]);
define("ryunosuke\\Functions\\Package\\optional", ["ryunosuke\\Functions\\Package\\Syntax", "optional"]);
define("ryunosuke\\Functions\\Package\\chain", ["ryunosuke\\Functions\\Package\\Syntax", "chain"]);
define("ryunosuke\\Functions\\Package\\throws", ["ryunosuke\\Functions\\Package\\Syntax", "throws"]);
define("ryunosuke\\Functions\\Package\\throw_if", ["ryunosuke\\Functions\\Package\\Syntax", "throw_if"]);
define("ryunosuke\\Functions\\Package\\blank_if", ["ryunosuke\\Functions\\Package\\Syntax", "blank_if"]);
define("ryunosuke\\Functions\\Package\\call_if", ["ryunosuke\\Functions\\Package\\Syntax", "call_if"]);
define("ryunosuke\\Functions\\Package\\switchs", ["ryunosuke\\Functions\\Package\\Syntax", "switchs"]);
define("ryunosuke\\Functions\\Package\\try_null", ["ryunosuke\\Functions\\Package\\Syntax", "try_null"]);
define("ryunosuke\\Functions\\Package\\try_return", ["ryunosuke\\Functions\\Package\\Syntax", "try_return"]);
define("ryunosuke\\Functions\\Package\\try_catch", ["ryunosuke\\Functions\\Package\\Syntax", "try_catch"]);
define("ryunosuke\\Functions\\Package\\try_finally", ["ryunosuke\\Functions\\Package\\Syntax", "try_finally"]);
define("ryunosuke\\Functions\\Package\\try_catch_finally", ["ryunosuke\\Functions\\Package\\Syntax", "try_catch_finally"]);
define("ryunosuke\\Functions\\Package\\get_uploaded_files", ["ryunosuke\\Functions\\Package\\Utility", "get_uploaded_files"]);
define("ryunosuke\\Functions\\Package\\cachedir", ["ryunosuke\\Functions\\Package\\Utility", "cachedir"]);
define("ryunosuke\\Functions\\Package\\cache", ["ryunosuke\\Functions\\Package\\Utility", "cache"]);
define("ryunosuke\\Functions\\Package\\parse_namespace", ["ryunosuke\\Functions\\Package\\Utility", "parse_namespace"]);
define("ryunosuke\\Functions\\Package\\resolve_symbol", ["ryunosuke\\Functions\\Package\\Utility", "resolve_symbol"]);
define("ryunosuke\\Functions\\Package\\parse_annotation", ["ryunosuke\\Functions\\Package\\Utility", "parse_annotation"]);
define("ryunosuke\\Functions\\Package\\is_ansi", ["ryunosuke\\Functions\\Package\\Utility", "is_ansi"]);
define("ryunosuke\\Functions\\Package\\ansi_colorize", ["ryunosuke\\Functions\\Package\\Utility", "ansi_colorize"]);
define("ryunosuke\\Functions\\Package\\process", ["ryunosuke\\Functions\\Package\\Utility", "process"]);
define("ryunosuke\\Functions\\Package\\arguments", ["ryunosuke\\Functions\\Package\\Utility", "arguments"]);
define("ryunosuke\\Functions\\Package\\stacktrace", ["ryunosuke\\Functions\\Package\\Utility", "stacktrace"]);
define("ryunosuke\\Functions\\Package\\backtrace", ["ryunosuke\\Functions\\Package\\Utility", "backtrace"]);
define("ryunosuke\\Functions\\Package\\profiler", ["ryunosuke\\Functions\\Package\\Utility", "profiler"]);
define("ryunosuke\\Functions\\Package\\error", ["ryunosuke\\Functions\\Package\\Utility", "error"]);
define("ryunosuke\\Functions\\Package\\add_error_handler", ["ryunosuke\\Functions\\Package\\Utility", "add_error_handler"]);
define("ryunosuke\\Functions\\Package\\timer", ["ryunosuke\\Functions\\Package\\Utility", "timer"]);
define("ryunosuke\\Functions\\Package\\benchmark", ["ryunosuke\\Functions\\Package\\Utility", "benchmark"]);
define("ryunosuke\\Functions\\Package\\stringify", ["ryunosuke\\Functions\\Package\\Vars", "stringify"]);
define("ryunosuke\\Functions\\Package\\numberify", ["ryunosuke\\Functions\\Package\\Vars", "numberify"]);
define("ryunosuke\\Functions\\Package\\numval", ["ryunosuke\\Functions\\Package\\Vars", "numval"]);
define("ryunosuke\\Functions\\Package\\arrayval", ["ryunosuke\\Functions\\Package\\Vars", "arrayval"]);
define("ryunosuke\\Functions\\Package\\arrayable_key_exists", ["ryunosuke\\Functions\\Package\\Vars", "arrayable_key_exists"]);
define("ryunosuke\\Functions\\Package\\attr_exists", ["ryunosuke\\Functions\\Package\\Vars", "attr_exists"]);
define("ryunosuke\\Functions\\Package\\attr_get", ["ryunosuke\\Functions\\Package\\Vars", "attr_get"]);
define("ryunosuke\\Functions\\Package\\si_prefix", ["ryunosuke\\Functions\\Package\\Vars", "si_prefix"]);
define("ryunosuke\\Functions\\Package\\si_unprefix", ["ryunosuke\\Functions\\Package\\Vars", "si_unprefix"]);
define("ryunosuke\\Functions\\Package\\is_empty", ["ryunosuke\\Functions\\Package\\Vars", "is_empty"]);
define("ryunosuke\\Functions\\Package\\is_primitive", ["ryunosuke\\Functions\\Package\\Vars", "is_primitive"]);
define("ryunosuke\\Functions\\Package\\is_recursive", ["ryunosuke\\Functions\\Package\\Vars", "is_recursive"]);
define("ryunosuke\\Functions\\Package\\is_stringable", ["ryunosuke\\Functions\\Package\\Vars", "is_stringable"]);
define("ryunosuke\\Functions\\Package\\is_arrayable", ["ryunosuke\\Functions\\Package\\Vars", "is_arrayable"]);
define("ryunosuke\\Functions\\Package\\is_countable", ["ryunosuke\\Functions\\Package\\Vars", "is_countable"]);
define("ryunosuke\\Functions\\Package\\varcmp", ["ryunosuke\\Functions\\Package\\Vars", "varcmp"]);
define("ryunosuke\\Functions\\Package\\var_type", ["ryunosuke\\Functions\\Package\\Vars", "var_type"]);
define("ryunosuke\\Functions\\Package\\var_apply", ["ryunosuke\\Functions\\Package\\Vars", "var_apply"]);
define("ryunosuke\\Functions\\Package\\var_applys", ["ryunosuke\\Functions\\Package\\Vars", "var_applys"]);
define("ryunosuke\\Functions\\Package\\var_export2", ["ryunosuke\\Functions\\Package\\Vars", "var_export2"]);
define("ryunosuke\\Functions\\Package\\var_html", ["ryunosuke\\Functions\\Package\\Vars", "var_html"]);
define("ryunosuke\\Functions\\Package\\var_pretty", ["ryunosuke\\Functions\\Package\\Vars", "var_pretty"]);
define("ryunosuke\\Functions\\Package\\console_log", ["ryunosuke\\Functions\\Package\\Vars", "console_log"]);
define("ryunosuke\\Functions\\Package\\hashvar", ["ryunosuke\\Functions\\Package\\Vars", "hashvar"]);